start_time: "2025-11-30T00:00:00Z"
stop_time: "2025-12-07T19:00:00Z"
inputs:
  - RAW_ADC_NO2_W
  - RAW_ADC_NO2_A
  - RAW_ADC_NO_W
  - RAW_ADC_NO_A
  - RAW_ADC_O3_W
  - RAW_ADC_O3_A
  - sht_temp
  - sht_humid
targets:
  - NO2

model_name: "NO2_ual-3"
model_version: "1"